name: PR Build Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run @keep-accounts-app/web:lint

      - name: Test
        run: npx nx run @keep-accounts-app/web:test

      - name: Build Web Application
        run: npx nx run @keep-accounts-app/web:build
